services:
  mysql:
    image: 'mysql:latest'
    environment:
      environment:
        - 'DB_URL=${DB_URL}'
        - 'DB_USERNAME=${DB_USERNAME}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
    ports:
      - '3306:3306'